/*Borrado y creación de 0 de todas las tablas*/
DROP TABLE PARTICIPAN;
DROP TABLE INGRESAN;
DROP TABLE GASTAN;
DROP TABLE ORGANIZAN;
DROP TABLE ATIENDEN;
DROP TABLE ASIENTOS_CONTABLES;
DROP TABLE CENTROS;
DROP TABLE CLIENTES;
DROP TABLE EMPLEADOS;
DROP TABLE ACTIVIDADES;
